smooch/smooch-docs

content/auth-messages.json

@jpjoyal 
I left the test content for now, it needs to be change or be an empty array before deploying the code in prod.

Auth page messages

---

Gruntfile.js
README.md
package.json

@juliangarritano @alavers @mspensieri @jpjoyal 
Will also follow with supportkit/supportkit-ios#66

Add Grunt tasks

---

source/includes/_adding_supportkit_js.md

Fix typo in require("supportkit")

---

Gruntfile.js
source/android/index.md
source/includes/users/_authenticating_users.md
source/ios/index.md

@dannytranlx @jpjoyal @kvgauthier

Update JWT docs

---

source/stylesheets/custom.scss

Restore language border

---

source/stylesheets/custom.scss

make platform button equal again

---

source/rest/index.md

@jpjoyal @dannytranlx @mspensieri

Fix outdated response bodies

---

source/layouts/3col.erb

@jpjoyal Was there a reason why you left that out?
With font:
Without font:
Life changing, right?

Add Proxima Nova font

---

source/includes/_configuring_push_ios.md

remove no password mention

---

source/rest/index.md

@lemieux @jugarrit @mspensieri

Document change making text replacable by mediaUrl and mediaType

---

source/rest/index.md

@mspensieri @lemieux @dannytranlx @jpjoyal @Mario54
docs for https://github.com/smooch/smooch/pull/556

Document POST /v1/appusers

---

source/includes/_welcome.md.erb
source/rest/index.md

@jpjoyal 
@mspensieri 
@alavers

Changed copy in welcome message and rest intro

---

source/includes/_getting_conversations_started.md
source/includes/_getting_conversations_started_js.md
source/includes/integrations/_zendesk.md

It should be the last ones :cry:

Update user-data link

---

source/includes/integrations/_slack.md

Explain how to get rid of 'fugly' slack channel names

---

source/includes/customization/_string_customization_android.md

@jpjoyal 
@alavers 
@spasiu 
@kvgauthier

Modified string customization docs for Android

---

source/includes/users/_authenticating_users.md
source/rest/index.md

@spasiu @jmtremblay @mspensieri

use consistent JWT terminology

---

README.md
source/rest/index.md

@lemieux @alavers @dannytranlx @jugarrit @spasiu @Mario54

Add expected status code for REST API responses. Remove beta tag

---

source/rest/index.md

Add API docs for unread count in conversation

---

source/includes/customization/_embedded_js.md
source/includes/customization/_string_customization_js.md
source/javascript/index.md

@dannytranlx @Mario54 @alavers @mspensieri

Add embedded mode instructions

---

source/javascripts/all_nohacks.js
source/javascripts/all_nohacks_nosearch.js
source/javascripts/app/lang.js
source/javascripts/lib/language_hack/lang.js
source/layouts/3col.erb
source/rest/index.md
source/stylesheets/custom.scss

Added new Javacript tab in the REST API docs.
@jpjoyal @alavers @Mario54 @dannytranlx @mspensieri

Smooch Core and the resurrection of language tabs

---

source/javascripts/app/lang.js
source/javascripts/lib/language_hack/lang.js

Set language suffix everywhere for storage

---

source/includes/customization/_string_customization_js.md

Some strings were missing. I'll merge and deploy.
@dannytranlx @Mario54 @alavers @mspensieri

Add settings strings for customization

---

source/rest/index.md

Add devices array to doc sample bodies

---

source/rest/index.md

@jpjoyal @dannytranlx @alavers @spasiu 
To be merged after https://github.com/smooch/smooch/pull/1093

Add mention of webhooks frontend and how to create a secret key

---

source/includes/customization/_string_customization.md

@jugarrit @dannytranlx @Mario54

Add iOS localization keys to strings customization section

---

source/android/index.md
source/includes/_configuring_push_ios.md
source/includes/integrations/_front.md
source/ios/index.md
source/javascript/index.md
source/rest/index.md

@alavers @dannytranlx @jugarrit @Mario54 
Will wait for next deploy of the backend to merge, since it relies on some stuff in integration

Add docs for Front, PUT device API, and enableAppDelegateSwizzling on iOS

---

source/rest/index.md

@alavers @mspensieri @jugarrit @lemieux

Add postback trigger to the webhooks documentation

---

source/rest/index.md

@Mario54 @dannytranlx @alavers @spasiu

Action buttons

---

source/android/index.md
source/includes/customization/_notification_action.md

@dannytranlx 
@jpjoyal 
@mspensieri 
@alavers

Add notification action override docs for Android

---

source/includes/messaging_channels/_messenger.md

@jpjoyal @mspensieri @chloepouprom 
Changed docs to reflect what's currently in prod

Update Messenger channel docs for blocked buy buttons

---

source/rest/index.md

@mspensieri @jugarrit @lemieux @dannytranlx @jpjoyal

Hide rest docs section headers for now

---

source/includes/business_app_integrations/_front.md

fix front link

---

pages/docs/becoming-an-integration-partner.md
pages/docs/oauth.md

@gozman @jpjoyal @debbiepapoulis @heatheratsmooch

Integration partner docs

---

data/channelCapabilities.js
pages/changelog.md

* Add changelog for Jan 19th, 2017
* Update channel capabilities grid

Deploy changelog

---

pages/changelog.md
pages/guide/native-ios-sdk.md

* Add documentation for location support on iOS
* Add changelog for Feb 14th, 2017
* Fix changelog description

Add docs for iOS location support (#244)

---

components/ChannelCapabilitiesGrid/index.js
data/channelCapabilities.js

Add location capabilities

---

pages/guide/web-messenger.md

Also fixed a couple of layout bugs.

Add mention of smooch-js peer dependencies when using NPM 3 (#251)

---

components/SiteNav.js
components/TwoColumnLayout.js
styles/content.less
styles/grid.less
styles/main.less
wrappers/md.js

* Make main container fluid
* Add event listener to all image, use zoom-in cursor on images

Improve image visibility (#266)

---

pages/changelog.md
slate/source/includes/rest/core/_conversations.md

* Display settings
* Changelog

Documentation for Messenger 1.4 Updates
